language: c++
dist: trusty
sudo: required

git:
  depth: 1

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
      env: COMPILER=gcc-6 COMPILERXX=g++-6
    - os: linux
      addons:
        apt:
          packages:
            - g++-6
            - clang-3.8
          sources:
            - ubuntu-toolchain-r-test
      env: COMPILER=clang-3.8 COMPILERXX=clang++-3.8 CXXFLAGS="-isystem /usr/include/c++/6"

install:
  - export CC=$COMPILER
  - export CXX=$COMPILERXX

script:
  - mkdir -p build && cd build && rm -rf *
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug
  - make && ctest
